### ISSUE TITLE
Packets

### ISSUE THREAD

**Issue by j0ach1mmall3** [TheLightMC/PocketServer#17]
How do I add packets to the PacketRegistry, and is it recommended to do so?

**Comment by DarkSeraphim** [comment]
Not that I would recommend it, assuming there's no modding community (yet). If you have packet fixes, we would prefer to have them PR'd anyway :smile:. Anyway, there is a method for it (because when I rewrote the PacketRegistry, I was pressed by @samczsun to allow it). PacketType is an interface, so you are allowed to do fuck all with it, as long as you don't breach the contracts set for it (currently not documented, check the code :cry:)

https://github.com/TheLightMC/PocketServer/blob/master/server/src/main/java/com/pocketserver/net/PacketRegistry.java#L157

**Comment by j0ach1mmall3** [comment]
Oh yea, but I mean, in the DefaultPacketType aren't all the Packets atm.
Even wiki.vg doesn't mention all (Complete list @ https://github.com/PocketMine/PocketMine-MP/tree/master/src/pocketmine/network/protocol)
That's why I wanted to add some, but I'm afraid I'll break something in that class...

**Comment by DarkSeraphim** [comment]
@j0ach1mmall3 adding packets to DefaultPacketType is always good!

**Comment by j0ach1mmall3** [comment]
Ok, how does the id work though? It's not consistent with wiki.vg

**Comment by DarkSeraphim** [comment]
@j0ach1mmall3 according to (iirc) @Fireflies wiki.vg is quite outdated, he based it on [MiNET documentation](https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Net/MCPE%20Protocol%20Documentation.md) which appears to be one of the most up to date protocol specs (last edited a couple of hours ago, rather than months).

**Comment by j0ach1mmall3** [comment]
Ah, I see, thanks for the link :)

**Comment by Fireflies** [comment]
>How do I add packets to the PacketRegistry, and is it recommended to do so?

Same way as we do, though with a few changes of course. Creating custom packets is definitely not recommended for now, but if you're implementing some more packets then go ahead as long as you make the code somewhat consistent with other packets. :stuck_out_tongue_winking_eye: 

@TheLightMC got in touch with AgentK on IRC who informed him of the status of the protocol docs and pointed him in the direction of MiNET. :smile:
